<?php

// phpcs:ignoreFile
// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model;

final class DateTime
{
    private $value;

    public function __construct(string $value)
    {
    	// support milliseconds in date time
		// can't just use "Y-m-d\TH:i:s.uP" because fit outputs 6 fraction digits and Assertion fails.
		if (false !== strpos($value, '.')) {
			$value = preg_replace('#\.\d{1,6}\+#', '+', $value); // just remove fraction
		}
        if (!\Assert\Assertion::date($value, \DateTime::ATOM, \sprintf('Value "%s" is not a valid ISO 8601 format.', $value))) {
            throw new \InvalidArgumentException('');
        }

        $this->value = $value;
    }

    public function value(): string
    {
        return $this->value;
    }

    public static function fromString(string $dateTime): DateTime
    {
        return new self($dateTime);
    }

    public function toString(): string
    {
        return $this->value;
    }

    public function __toString(): string
    {
        return $this->value;
    }
}
